#   Copyright (C) 2026 John Törnblom
#
# This file is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; see the file COPYING. If not see
# <http://www.gnu.org/licenses/>.

PYTHON := python3

CFLAGS := -Wall -Werror
CFLAGS += `pkg-config libxml-2.0 --cflags`

SRCS := src/main-pc.c src/srv.c src/mime.c src/asset.c src/mdns.c src/smb.c
SRCS += src/http.c src/dlna.c src/fs.c src/viz.c

LDADD  += `pkg-config libmicrohttpd --libs`
LDADD  += `pkg-config microdns --libs`
LDADD  += `pkg-config libsmb2 --libs`
LDADD  += `pkg-config libcurl --libs`
LDADD  += `pkg-config libxml-2.0 --libs`
LDADD  += `pkg-config libavcodec --libs`
LDADD  += `pkg-config libavformat --libs`
LDADD  += `pkg-config libswresample --libs`
LDADD  += `pkg-config libswscale --libs`
LDADD  += `pkg-config libavutil --libs`
LDADD  += -lm

all: jtplay-srv.elf

src/asset.c: src/asset_bundle.inc

src/asset_bundle.inc:
	$(PYTHON) tools/gen-asset-module.py assets > $@

jtplay-srv.elf: $(SRCS)
	$(CC) $(CFLAGS) -o $@ $^ $(LDADD)

test: jtplay-srv.elf
	./jtplay-srv.elf

clean:
	rm -rf *.elf *.o src/asset_bundle.inc

